const PLAYLIST_SONGS = [
  { title: "James Dean", artist: "CairokeeOfficial", ytId: "m540R-vGLlI", artworkUrl: "https://i.ytimg.com/vi/m540R-vGLlI/hqdefault.jpg" },
  { title: "Kelma", artist: "Ramy Sabry", ytId: "XDrNd5qkza4", artworkUrl: "https://i.ytimg.com/vi/XDrNd5qkza4/hqdefault.jpg" },
  { title: "Heseeny", artist: "TUL8TE", ytId: "bcMIr1xhXQI", artworkUrl: "https://i.ytimg.com/vi/bcMIr1xhXQI/hqdefault.jpg" },
  { title: "Nefsy Ahbek", artist: "CairokeeOfficial", ytId: "NGiRwLC3Xc8", artworkUrl: "https://i.ytimg.com/vi/NGiRwLC3Xc8/hqdefault.jpg" },
  { title: "Khalik Ma'aya", artist: "Amr Diab", ytId: "bmbHfXq2CAc", artworkUrl: "https://i.ytimg.com/vi/bmbHfXq2CAc/hqdefault.jpg" },
  { title: "Mesh Habibi Bas", artist: "Angham", ytId: "SYLHTvxe7NQ", artworkUrl: "https://i.ytimg.com/vi/SYLHTvxe7NQ/hqdefault.jpg" },
  { title: "We Akhyran", artist: "Mahmoud El Esseily | محمود العسيلي", ytId: "v41hcsVUbV0", artworkUrl: "https://i.ytimg.com/vi/v41hcsVUbV0/hqdefault.jpg" },
  { title: "Athadda Al Aalam", artist: "Saber Rebai", ytId: "CqWNFChfCl4", artworkUrl: "https://i.ytimg.com/vi/CqWNFChfCl4/hqdefault.jpg" },
  { title: "Hob Taht El Enshaa", artist: "Amir Eid", ytId: "JmUBIwK7d-E", artworkUrl: "https://i.ytimg.com/vi/JmUBIwK7d-E/hqdefault.jpg" },
  { title: "Ymken Kher", artist: "Ramy Sabry", ytId: "WgrLAh4BxPo", artworkUrl: "https://i.ytimg.com/vi/WgrLAh4BxPo/hqdefault.jpg" },
  { title: "Amarain", artist: "Amr Diab", ytId: "P1VVPMwGgPs", artworkUrl: "https://i.ytimg.com/vi/P1VVPMwGgPs/hqdefault.jpg" },
  { title: "حبيبي ليه", artist: "TUL8TE", ytId: "MLgCidfXl4Y", artworkUrl: "https://i.ytimg.com/vi/MLgCidfXl4Y/hqdefault.jpg" },
  { title: "هنا مصر هفضل كل مرة اجيلك", artist: "Mahmoud El Esseily | محمود العسيلي", ytId: "-2fGsXONSMU", artworkUrl: "https://i.ytimg.com/vi/-2fGsXONSMU/hqdefault.jpg" },
  { title: "Najwa Karam ... Aam Bimzah Maak | نجوى كرم ... عم بمزح معك", artist: "Rotana", ytId: "C_Z6djJNT7Y", artworkUrl: "https://i.ytimg.com/vi/C_Z6djJNT7Y/hqdefault.jpg" },
  { title: "انا نجم - من مسلسل ريفو", artist: "ريفو شو - Topic", ytId: "l9UQabALQZA", artworkUrl: "https://i.ytimg.com/vi/l9UQabALQZA/hqdefault.jpg" },
  { title: "Basrah w Atooh", artist: "CairokeeOfficial", ytId: "948wqojRi4I", artworkUrl: "https://i.ytimg.com/vi/948wqojRi4I/hqdefault.jpg" },
  { title: "Najwa Karam - Rouh Rouhi / نجوى كرم - روح روحي", artist: "Rotana", ytId: "-ZTMCkDPFvQ", artworkUrl: "https://i.ytimg.com/vi/-ZTMCkDPFvQ/hqdefault.jpg" },
  { title: "Maghroumah", artist: "Najwa Karam", ytId: "u-0-AkkuMJ8", artworkUrl: "https://i.ytimg.com/vi/u-0-AkkuMJ8/hqdefault.jpg" },
  { title: "ياسمين علي _نقابل ناس_الاغنية الاصلية كاملة2019", artist: "JAB", ytId: "S4j7cKGymhI", artworkUrl: "https://i.ytimg.com/vi/S4j7cKGymhI/hqdefault.jpg" },
  { title: "Yazan Haifawi - Wainek Min Zaman | يزن حيفاوي - وينك من زمان", artist: "Yazan Haifawi - يزن حيفاوي", ytId: "rbPcNV0gfLA", artworkUrl: "https://i.ytimg.com/vi/rbPcNV0gfLA/hqdefault.jpg" },
  { title: "Haygely Mawgow3", artist: "Tamer Ashour", ytId: "6r2nBhBUYHs", artworkUrl: "https://i.ytimg.com/vi/6r2nBhBUYHs/hqdefault.jpg" },
  { title: "Koul Waad", artist: "Wael Jassar - Topic", ytId: "8sbWhSQ9Dx4", artworkUrl: "https://i.ytimg.com/vi/8sbWhSQ9Dx4/hqdefault.jpg" },
  { title: "وائل جسار - بتوحشيني | Wael Jassar - Betew7ashini", artist: "ArabicaTV", ytId: "rngxuyPZ7Zo", artworkUrl: "https://i.ytimg.com/vi/rngxuyPZ7Zo/hqdefault.jpg" },
  { title: "Nasini El Donya", artist: "Ragheb Alama", ytId: "LHRzANXJEEM", artworkUrl: "https://i.ytimg.com/vi/LHRzANXJEEM/hqdefault.jpg" },
  { title: "We Maloh", artist: "Amr Diab", ytId: "n45XOgKijec", artworkUrl: "https://i.ytimg.com/vi/n45XOgKijec/hqdefault.jpg" },
  { title: "Kel El Qasayed", artist: "Marwan Khoury | مروان خوري", ytId: "5EgyhbdSZoU", artworkUrl: "https://i.ytimg.com/vi/5EgyhbdSZoU/hqdefault.jpg" },
  { title: "Mafi Mennik", artist: "Aziz Maraka", ytId: "K4NACOEF0Qo", artworkUrl: "https://i.ytimg.com/vi/K4NACOEF0Qo/hqdefault.jpg" },
  { title: "Narein", artist: "TUL8TE", ytId: "JnCTOi2QAZk", artworkUrl: "https://i.ytimg.com/vi/JnCTOi2QAZk/hqdefault.jpg" },
  { title: "Ana Baashaak Live", artist: "Nancy Ajram", ytId: "xdc7D2D3EKU", artworkUrl: "https://i.ytimg.com/vi/xdc7D2D3EKU/hqdefault.jpg" },
  { title: "Aayshalak", artist: "Elissa", ytId: "hODVrXRGsY4", artworkUrl: "https://i.ytimg.com/vi/hODVrXRGsY4/hqdefault.jpg" },
  { title: "Laiel El Ashekin", artist: "Georges Wassouf", ytId: "rQ7CahWbJUo", artworkUrl: "https://i.ytimg.com/vi/rQ7CahWbJUo/hqdefault.jpg" },
  { title: "Wehyaty Andak", artist: "Zekra", ytId: "X8XRKItBWi8", artworkUrl: "https://i.ytimg.com/vi/X8XRKItBWi8/hqdefault.jpg" },
  { title: "وائل جسار - خليني ذكرى | Wael Jassar - Khaleni Zekra", artist: "ArabicaTV", ytId: "Dnwa8_03ULY", artworkUrl: "https://i.ytimg.com/vi/Dnwa8_03ULY/hqdefault.jpg" },
  { title: "Je T’aime", artist: "Lara Fabian", ytId: "vz0OIwXOOYE", artworkUrl: "https://i.ytimg.com/vi/vz0OIwXOOYE/hqdefault.jpg" },
  { title: "Et si tu n'existais pas", artist: "Joe Dassin", ytId: "EJLDd-VOH1U", artworkUrl: "https://i.ytimg.com/vi/EJLDd-VOH1U/hqdefault.jpg" },
  { title: "Fayrouz - Habaitak Belsaif / فيروز - حبيتك بالصيف", artist: "arabicmusicroots", ytId: "WWllBI4oheI", artworkUrl: "https://i.ytimg.com/vi/WWllBI4oheI/hqdefault.jpg" },
  { title: "Majida El Roumi - Esmaa Alby / ماجدة الرومي - اسمع قلبي", artist: "WATARY", ytId: "DDr9MpVV2GM", artworkUrl: "https://i.ytimg.com/vi/DDr9MpVV2GM/hqdefault.jpg" },
  { title: "ŸUMA - Nghir Alik | نغير عليك  (Official Video)", artist: "Ÿuma", ytId: "sTXv0sPgjXY", artworkUrl: "https://i.ytimg.com/vi/sTXv0sPgjXY/hqdefault.jpg" },
  { title: "Bahaa Sultan - Ya Tara (Music Video) | (بهاء سلطان - يا ترى (فيديو كليب", artist: "Free Music \"Nasr Mahrous\"", ytId: "HrcGwDdti7Q", artworkUrl: "https://i.ytimg.com/vi/HrcGwDdti7Q/hqdefault.jpg" },
  { title: "Hob Hayaty", artist: "Bahaa Sultan FM", ytId: "hMh9fwZnNDo", artworkUrl: "https://i.ytimg.com/vi/hMh9fwZnNDo/hqdefault.jpg" },
  { title: "Je veux", artist: "Zaz", ytId: "Z7cuTnbF-2c", artworkUrl: "https://i.ytimg.com/vi/Z7cuTnbF-2c/hqdefault.jpg" },
  { title: "صحاك الشوق", artist: "Fadel Chaker", ytId: "0B3tagy4eBc", artworkUrl: "https://i.ytimg.com/vi/0B3tagy4eBc/hqdefault.jpg" },
  { title: "ماتيجي اعدي عليكي", artist: "TUL8TE", ytId: "_MuRtKVA7w4", artworkUrl: "https://i.ytimg.com/vi/_MuRtKVA7w4/hqdefault.jpg" },
  { title: "أحلى رسمه", artist: "Fadel Chaker", ytId: "dk2tFHCWb2s", artworkUrl: "https://i.ytimg.com/vi/dk2tFHCWb2s/hqdefault.jpg" },
  { title: "Maghrorah", artist: "Release - Topic", ytId: "H6QV6vG8SfU", artworkUrl: "https://i.ytimg.com/vi/H6QV6vG8SfU/hqdefault.jpg" },
  { title: "Helwa Ya Baladi", artist: "Dalida", ytId: "39RHI3ZZwLc", artworkUrl: "https://i.ytimg.com/vi/39RHI3ZZwLc/hqdefault.jpg" },
  { title: "Matrahak Bi Albi", artist: "Magida El Roumi", ytId: "D450gaz-Xqo", artworkUrl: "https://i.ytimg.com/vi/D450gaz-Xqo/hqdefault.jpg" },
  { title: "Abdel Halim Hafez - Awel Mara | عبد الحليم حافظ - أول مره تحب ياقلبى", artist: "Abdel Halim Hafez - عبد الحليم حافظ", ytId: "qhqJYGn5x5E", artworkUrl: "https://i.ytimg.com/vi/qhqJYGn5x5E/hqdefault.jpg" },
  { title: "Ana Ghaltan", artist: "Bahaa Sultan FM", ytId: "515OrfbY324", artworkUrl: "https://i.ytimg.com/vi/515OrfbY324/hqdefault.jpg" },
  { title: "Misr Italia Properties - Ahlamna - Angham and Cairokee - Ramadan 2023", artist: "Misr Italia Properties", ytId: "TtexFbGjS8w", artworkUrl: "https://i.ytimg.com/vi/TtexFbGjS8w/hqdefault.jpg" },
  { title: "مفاجأة. الكينج منير مع أمير عيد", artist: "sayed sallam", ytId: "0pdeBt1o_zE", artworkUrl: "https://i.ytimg.com/vi/0pdeBt1o_zE/hqdefault.jpg" },
  { title: "Bayent El Hob Alaya", artist: "Mayada El Hennawy - ميادة الحناوي", ytId: "63Oe7moEdao", artworkUrl: "https://i.ytimg.com/vi/63Oe7moEdao/hqdefault.jpg" },
  { title: "أغنية يا ما نفسي أقولك - دنيا سمير غانم - من مسلسل عايشة الدور  #دنيا_سمير_غانم", artist: "أصفر ", ytId: "PsCeX5eH5gs", artworkUrl: "https://i.ytimg.com/vi/PsCeX5eH5gs/hqdefault.jpg" },
  { title: "C'est toi que jaime", artist: "Cheb Amrou - Topic", ytId: "9woRPqcS63c", artworkUrl: "https://i.ytimg.com/vi/9woRPqcS63c/hqdefault.jpg" },
  { title: "Wayah", artist: "Amr Diab", ytId: "4hfj4OIWQ-0", artworkUrl: "https://i.ytimg.com/vi/4hfj4OIWQ-0/hqdefault.jpg" },
  { title: "Sabah - Yana Yana | Official Music Video | صباح - يانا يانا", artist: "Mazzika - مزيكا", ytId: "89tokXyVp0o", artworkUrl: "https://i.ytimg.com/vi/89tokXyVp0o/hqdefault.jpg" },
  { title: "Abdel Halim Hafez - Sawwah | Live Record | عبد الحليم حافظ - سواح", artist: "Abdel Halim Hafez - عبد الحليم حافظ", ytId: "LFO2doiRHMI", artworkUrl: "https://i.ytimg.com/vi/LFO2doiRHMI/hqdefault.jpg" },
  { title: "على حسب وداد قلبي (Live)", artist: "Abdel Halim Hafez - عبد الحليم حافظ", ytId: "JvuUzJHDBmM", artworkUrl: "https://i.ytimg.com/vi/JvuUzJHDBmM/hqdefault.jpg" },
  { title: "Helaf El Amar", artist: "Georges Wassouf", ytId: "R96pix7Zx2w", artworkUrl: "https://i.ytimg.com/vi/R96pix7Zx2w/hqdefault.jpg" },
  { title: "Zein Obeid - Asaab Kelmi Bfaker Fiha [Biel Concert Live Performance]/ زين عبيد - اصعب كلمه بفكر فيها", artist: "Jean-Marie Riachi", ytId: "OVUF3-X27oU", artworkUrl: "https://i.ytimg.com/vi/OVUF3-X27oU/hqdefault.jpg" },
  { title: "Ana Mn Gherak", artist: "Bahaa Sultan FM", ytId: "Us3y7js9SO8", artworkUrl: "https://i.ytimg.com/vi/Us3y7js9SO8/hqdefault.jpg" },
  { title: "Cyrine Abdul Noor - Law Bass Fe Eyne | Official Music Video | سيرين عبد النور - لو بص في عيني", artist: "Rotana", ytId: "5mJ1xTHYFEw", artworkUrl: "https://i.ytimg.com/vi/5mJ1xTHYFEw/hqdefault.jpg" },
  { title: "Warda - Aal Eih Beyesaloon | Live Record | وردة - قال إيه بيسألوني", artist: "Warda - وردة", ytId: "NdlhemOg_YU", artworkUrl: "https://i.ytimg.com/vi/NdlhemOg_YU/hqdefault.jpg" },
  { title: "Nancy Ajram - Mestaniak (Live) / نانسي عجرم - مستنياك", artist: "Nancy Ajram", ytId: "ShMfhK_ZTQI", artworkUrl: "https://i.ytimg.com/vi/ShMfhK_ZTQI/hqdefault.jpg" },
];
